# Generated by Django 5.2.1 on 2025-05-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_author_book_market_price_book_pub_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='xxx@yyyy.zzz', max_length=254, verbose_name='邮箱'),
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True, verbose_name='妻子姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.author', verbose_name='丈夫')),
            ],
        ),
    ]
