# Generated by Django 5.2.1 on 2025-06-07 16:25

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0002_reader_downloadrecord_book_reader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': '电子书', 'verbose_name_plural': '电子书'},
        ),
        migrations.AlterModelOptions(
            name='bookfile',
            options={'verbose_name': '电子书文件', 'verbose_name_plural': '电子书文件'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '书籍分类', 'verbose_name_plural': '书籍分类'},
        ),
        migrations.AlterModelOptions(
            name='downloadrecord',
            options={'ordering': ['-downloaded_at'], 'verbose_name': '下载记录', 'verbose_name_plural': '下载记录'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': '读者', 'verbose_name_plural': '读者'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '书籍标签', 'verbose_name_plural': '书籍标签'},
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.AddField(
            model_name='bookfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小（字节）'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True, verbose_name='URL标识'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='下载IP'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='用户代理'),
        ),
        migrations.AddField(
            model_name='reader',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='该用户所属的用户组', related_name='reader_groups', related_query_name='reader', to='auth.group', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='reader',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AddField(
            model_name='reader',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='reader',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='该用户拥有的直接权限', related_name='reader_user_permissions', related_query_name='reader', to='auth.permission', verbose_name='用户权限'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True, verbose_name='URL标识'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.cover_upload_path, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(upload_to=books.models.book_file_upload_path, verbose_name='文件路径'),
        ),
    ]
